version: '3'

services:
  dog-server:
    image: nginx
    container_name: dog
    volumes:
      - ./dog-server:/usr/share/nginx/html
    ports:
      - 7100:80
  
  cat-server:
    image: nginx
    container_name: cat
    volumes:
      - ./cat-server:/usr/share/nginx/html
    ports:
      - 7101:80
  
  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80